language: ruby
sudo: required
rvm:
- 2.7.0
services:
  - mysql
before install:
  - sudo cp $TRAVIS_BUILD_DIR/mysql.cnf /etc/mysql/conf.d/
  - sudo service mysql restart
script:
  - 'bundle exec rake db:setup'
  - 'bundle exec rake spec'
